format = """
[](#000000)\
$username\
[](bg:#00FF23 fg:#000000)\
$directory\
[](fg:#00FF23 bg:#008F17)\
$git_branch\
$git_status\
[](fg:#008F17 bg:#004F0E)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$python\
[](fg:#004F0E bg:#002808)\
$docker_context\
[](fg:#002808 bg:#001404)\
$time\
[ ](fg:#001404)\
\n$character
"""
command_timeout = 5000

[username]
show_always = true
style_user = "bg:#000000 fg:#00FF23"
style_root = "bg:#000000 fg:#00FF23"
format = '[$user ]($style)'

[directory]
style = "bg:#00FF23 fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[os]
disabled = false
style = "bg:color_accent fg:color_fg0"

[os.symbols]
Linux = "󰌽"
Arch = "󰣇"
Fedora = "󰣛"
Debian = "󰣚"
Ubuntu = "󰕈"
Macos = "󰀵"

[c]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#002808 fg:#000000"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#008F17 fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#008F17 fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#000000 fg:#00FF23"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#004F0E fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#001404 fg:#00FF23"
format = '[ $time ]($style)'
